################################################################
################################################################
#######################    Config    ###########################
################################################################
################################################################



########################################
############  General  #################
########################################

Lang: "en_US"


########################################
###########  Database  #################
########################################

## MySQL Login ##
## You should never use the root User for security reasons ##
## If you don't use MySQL, you can ignore this part ##
Host: "localhost"
Port: 3306
Database: "template"
Username: "admin"
Password: "admin"